import turtle

#initialize method
Fabian=turtle.Turtle()


Fabian.pensize(12)
Fabian.color("black")
Fabian.shape('turtle')
Fabian.left(180)
Fabian.forward(100)
Fabian.left(90)
Fabian.forward(150)
Fabian.left(180)
Fabian.forward(75)
Fabian.right(90)
Fabian.forward(50)

#initialize method
Fabian=turtle.Turtle()

Fabian.pensize(12)
Fabian.color("green")
Fabian.shape('turtle')
Fabian.penup()
Fabian.forward(20)
Fabian.pendown()
Fabian.left(250)
Fabian.forward(160)
Fabian.backward(160)
Fabian.left(40)
Fabian.forward(160)
Fabian.backward(80)
Fabian.right(110)
Fabian.forward(50)

Fabian=turtle.Turtle()

Fabian.pensize(12)
Fabian.color("yellow")
Fabian.shape('turtle')
Fabian.penup()
Fabian.forward(100)
Fabian.pendown()
Fabian.left(270)
Fabian.forward(150)
Fabian.backward(160)
Fabian.right(0)
Fabian.forward(45)
Fabian.circle(40)
Fabian.penup()
Fabian.forward(70)
Fabian.pendown()
Fabian.right(0)
Fabian.circle(40)


Fabian=turtle.Turtle()

Fabian.pensize(12)
Fabian.color("red")
Fabian.shape('turtle')
Fabian.penup()
Fabian.forward(220)
Fabian.pendown()
Fabian.left(270)
Fabian.forward(150)
Fabian.penup()
Fabian.backward(170)
Fabian.pendown()
Fabian.circle(1)

Fabian=turtle.Turtle()

Fabian.pensize(12)
Fabian.color("green")
Fabian.shape('turtle')
Fabian.penup()
Fabian.forward(290)
Fabian.pendown()
Fabian.left(250)
Fabian.forward(160)
Fabian.backward(160)
Fabian.left(40)
Fabian.forward(160)
Fabian.backward(80)
Fabian.right(110)
Fabian.forward(50)

Fabian=turtle.Turtle()

Fabian.pensize(12)
Fabian.color("brown")
Fabian.shape('turtle')
Fabian.penup()
Fabian.forward(380)
Fabian.pendown()
Fabian.left(270)
Fabian.forward(150)
Fabian.penup()
Fabian.backward(150)
Fabian.pendown()
Fabian.right(345)
Fabian.forward(155)
Fabian.left(165)
Fabian.forward(150)
turtle.done()